name: grist

services:
  grist:
    image: gristlabs/grist:${TAG:-latest}
    ports:
      - "${PORT:-8485}:8484"
    environment:
      APP_HOME_URL: ${APP_HOME_URL}
      GRIST_SESSION_SECRET: ${GRIST_SESSION_SECRET}
      GRIST_DEFAULT_EMAIL: ${GRIST_DEFAULT_EMAIL}
      GRIST_FORWARD_AUTH_HEADER: X-authentik-email
      GRIST_FORCE_LOGIN: "true"
    volumes:
      - grist-data:/persist
    restart: always

volumes:
  grist-data:
